stages:
  - lint
  - test
  - deploy

# Linting stage
lint:
  stage: lint
  image: python:3.12  # or your preferred Python version
  script:
    - pip install -r requirements.txt  # Install dependencies
    - pip install black flake8  # Install Black and Flake8
    - flake8 . --exclude venv,.venv,__pycache__,.tox,.nox,.coverage,*.egg-info,dist  # Run flake8 with exclusions
    - black . --exclude "venv|.venv|__pycache__|\.tox|\.nox|\.coverage|*.egg-info|dist"  # Run Black with exclusions

# Testing stage (optional, for pytest)
test:
  stage: test
  image: python:3.12  # or your preferred Python version
  script:
    - pip install -r requirements.txt  # Install dependencies
    - pip install pytest  # Install pytest
    - pytest  # Run tests

# Deployment stage (if you need to deploy, adjust this to your requirements)
deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."