stages:
  - lint
  - test
  - deploy

# Linting stage
lint:
  stage: lint
  image: python:3.12  # or your preferred Python version
  script:
    - pip install -r requirements.txt  # Install dependencies
    - pip install black flake8  # Install Black and Flake8
    - flake8 --exclude=venv/  # Run Flake8 with exclusions
    - black . --exclude "venv|.venv|__pycache__|\.tox|\.nox|\.coverage|.*egg-info|dist"  # Run Black with exclusionsn Black with exclusions

# Testing stage (optional, for pytest)
test:
  stage: test
  image: python:3.12  # Or your preferred Python version
  script:
    - pip install -r requirements.txt  # Install dependencies
    - pip install pytest  # Install pytest
    - |
      if pytest --collect-only > /dev/null 2>&1; then
        pytest
      else
        echo "No tests to run."
      fi


deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
